// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaladinsLoadoutSelector.Data;

namespace PaladinsLoadoutSelector.Data.Migrations
{
    [DbContext(typeof(PaladinsLoudoutSelectorContext))]
    [Migration("20180722212906_add-loadoutcard")]
    partial class addloadoutcard
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaladinsDomain.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChampionId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("PaladinsDomain.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("PaladinsDomain.Loadout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChampionId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.ToTable("Loadouts");
                });

            modelBuilder.Entity("PaladinsDomain.LoadoutCard", b =>
                {
                    b.Property<int>("CardId");

                    b.Property<int>("LoadoutId");

                    b.Property<int>("Level");

                    b.HasKey("CardId", "LoadoutId");

                    b.HasIndex("LoadoutId");

                    b.ToTable("LoadoutCards");
                });

            modelBuilder.Entity("PaladinsDomain.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("PaladinsDomain.Card", b =>
                {
                    b.HasOne("PaladinsDomain.Champion", "Champion")
                        .WithMany()
                        .HasForeignKey("ChampionId");
                });

            modelBuilder.Entity("PaladinsDomain.Loadout", b =>
                {
                    b.HasOne("PaladinsDomain.Champion", "Champion")
                        .WithMany("Loadouts")
                        .HasForeignKey("ChampionId");
                });

            modelBuilder.Entity("PaladinsDomain.LoadoutCard", b =>
                {
                    b.HasOne("PaladinsDomain.Card", "Card")
                        .WithMany("Loadouts")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PaladinsDomain.Loadout", "Loadout")
                        .WithMany("LoadoutCards")
                        .HasForeignKey("LoadoutId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
